# ACI playbook
---
- name: playbook for aci testing
  hosts: apic
  gather_facts: no

  tasks:
    - name: "Query Nodes"
      aci_fabric_node:
        host: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        state: query
      register: json_response

    - name: parse fabric nodes
      set_fact:
        nodes: "{{ item.fabricNodeIdentP.attributes.serial + ' is ' + item.fabricNodeIdentP.attributes.name }}"
      with_items: "{{ json_response.current }}"
      register: nodes_json

    - name: compile list of nodes
      set_fact:
        nodes: "{{ nodes_json.results | map(attribute='ansible_facts.nodes') | list }}"

    - name: print nodes
      debug: var=nodes
