# ACI playbook
---
- name: playbook for aci testing
  hosts: apic_234
  gather_facts: no

  tasks:
    - name: "Query Tenant"
      aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        state: query
      register: all_tenants

    - name: Create list of just tenants names
      set_fact:
        tenant_names: "{{ all_tenants | json_query('current[*].fvTenant.attributes.name') }}"

    - name: print list tenants names
      debug: var=tenant_names


